package soac.miniprojet.model.beans;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import java.io.Serializable;
import java.util.Date;

/**
 * StudentsBiblioInscId generated by hbm2java
 */
public class StudentsBiblioInsc implements Serializable {

	private Students student;
	private Date dateInsc;
	private InscriptionPeriod inscPeriod;
	private int id;

	public StudentsBiblioInsc() {
	}

	public Students getStudent() {
		return student;
	}

	public void setStudent(Students student) {
		this.student = student;
	}

	public Date getDateInsc() {
		return dateInsc;
	}

	public void setDateInsc(Date dateInsc) {
		this.dateInsc = dateInsc;
	}

    public InscriptionPeriod getInscPeriod() {
        return inscPeriod;
    }

    public void setInscPeriod(InscriptionPeriod inscPeriod) {
        this.inscPeriod = inscPeriod;
    }

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
}
