package soac.miniprojet.model.beans;
// Generated 7 janv. 2020 11:56:55 by Hibernate Tools 5.4.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Students generated by hbm2java
 */
public class Students implements java.io.Serializable {

    private int id;
    private String nom;
    private String prenom;
    private Date dateNaiss;
    private String sexe;
    private String numBac;
    private Date dateInsc;

    public Students() {
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public Date getDateNaiss() {
        return this.dateNaiss;
    }

    public void setDateNaiss(Date dateNaiss) {
        this.dateNaiss = dateNaiss;
    }

    public String getSexe() {
        return this.sexe;
    }

    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    public String getNumBac() {
        return this.numBac;
    }

    public void setNumBac(String numBac) {
        this.numBac = numBac;
    }

    public Date getDateInsc() {
        return this.dateInsc;
    }

    public void setDateInsc(Date dateInsc) {
        this.dateInsc = dateInsc;
    }

    @Override
    public String toString() {
        return "Students{" +
                "id=" + id +
                ", nom='" + nom + '\'' +
                ", prenom='" + prenom + '\'' +
                ", dateNaiss=" + dateNaiss +
                ", sexe='" + sexe + '\'' +
                ", numBac='" + numBac + '\'' +
                ", dateInsc=" + dateInsc +
                '}';
    }
}
